name: 'issue-creator'
description: 'Periodically create GitHub issue'
inputs:
  template-issue:
    description: 'Specify the issue number of the template in the repository. e.g. 1'
    default: ""
    required: false
  template-issue-url:
    description: 'Specify the issue url of the template. e.g. https://github.com/rerost/issue-creator/issues/1'
    default: ""
    required: false
  close-last-issue:
    description: 'If true, issue-creator closes the previous issue.'
    default: true
  check-before-create-issue:
    description: 'The issue will be created only when the status code of this script is 0.'
    default: "echo 'OK'"
  token:
    default: ${{ github.token }}
  discussion:
    description: 'If true, creates a discussion instead.'
    default: false
  repository:
    description: 'Specify a repository where the issue will be created. e.g. rerost/issue-creator'
    default: ${{ github.repository }}
runs:
  using: "docker"
  image: 'Dockerfile.actions'
  args:
    - ${{ inputs.template-issue-url }}
    - ${{ inputs.repository }}
    - ${{ inputs.template-issue }}
    - ${{ inputs.close-last-issue }}
    - ${{ inputs.check-before-create-issue }}
    - ${{ inputs.token }}
    - ${{ inputs.discussion }}
